### ISSUE TITLE
precomputed

### ISSUE THREAD

**Issue by StojiljkovicVetAna** [guiwitz/napari-morphodynamics#11]
Currently, the precomputed option doesn't load the segmented images with the following error message: 

Traceback (most recent call last):
  File "C:\Users\anast\OneDrive\Documents\Arbeit 2023\Guillaume Witz\Morphodynamics_Ana\Fork_Ana\napari-morphodynamics\src\napari_morphodynamics\napari_gui.py", line 479, in _on_run_segmentation
    self.res, _ = segment_and_track(
  File "C:\Users\anast\OneDrive\Documents\Arbeit 2023\Guillaume Witz\Morphodynamics_Ana\Fork_Ana\MorphoDynamics\morphodynamics\analysis_par.py", line 127, in segment_and_track
    res = initialize_analysis(data, param, model=None)
  File "C:\Users\anast\OneDrive\Documents\Arbeit 2023\Guillaume Witz\Morphodynamics_Ana\Fork_Ana\MorphoDynamics\morphodynamics\analysis_par.py", line 93, in initialize_analysis
    location, J, I = calibration(data, param, model)
  File "C:\Users\anast\OneDrive\Documents\Arbeit 2023\Guillaume Witz\Morphodynamics_Ana\Fork_Ana\MorphoDynamics\morphodynamics\analysis_par.py", line 255, in calibration
    location = center_of_mass(m)
UnboundLocalError: local variable 'm' referenced before assignment

**Comment by guiwitz** [comment]
Fixed in Morphodynamics via https://github.com/guiwitz/MorphoDynamics/commit/b517946834a9981b064b8ebf9656c59f0243f84c. Also added the possibility to use any label layer (e.g. hand annotation) as precomputed data via https://github.com/guiwitz/napari-morphodynamics/commit/4933f92e4a8aa99dc5bbbbf196a0d7936994ceac
